import React from 'react';
import { motion } from 'framer-motion';
import SEO from '../components/SEO';

export default function Privacy() {
  return (
    <div className="pt-32 pb-24 bg-white dark:bg-gray-950 min-h-screen transition-colors duration-500">
      <SEO title="Privacy Policy" description="How Zumm handles and protects your data in Healthcare, Insurance, and Legal workflows." />
      <div className="max-w-4xl mx-auto px-6 md:px-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="prose prose-slate dark:prose-invert max-w-none text-slate-900 dark:text-gray-300"
        >
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white mb-2 font-display">Privacy Policy</h1>
          <p className="text-slate-500 dark:text-gray-400 text-lg mb-12">Last Updated: March 30, 2026</p>
          
          <div className="p-6 bg-slate-50 dark:bg-gray-900 rounded-2xl border border-slate-200 dark:border-white/10 mb-12">
            <h4 className="text-slate-900 dark:text-white font-bold mb-2">Our Commitment</h4>
            <p className="text-sm text-slate-600 dark:text-gray-400 m-0">Zumm Inc. ("Zumm", "we", "us") is dedicated to protecting the sensitive documentation of our Enterprise partners. We operate with a security-first mindset, specifically tailored for the high-compliance needs of Healthcare, Insurance, and Legal industries.</p>
          </div>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. Data We Process</h2>
            <p>To provide our document intelligence services, we process several categories of data:</p>
            <ul className="space-y-4">
              <li>
                <strong>Customer Documents:</strong> We process unstructured documentation (PDFs, images, text) uploaded by our customers. This may include Protected Health Information (PHI), PII, or sensitive legal discovery files.
              </li>
              <li>
                <strong>Extracted Insights:</strong> Structured data generated by our AI engine, including medical codes, policy timelines, and contract entities.
              </li>
              <li>
                <strong>Account Information:</strong> Business contact details used for authentication and billing.
              </li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. High-Compliance Standards</h2>
            <p>Our infrastructure is designed for the most sensitive data environments:</p>
            <ul className="space-y-2">
              <li><strong>HIPAA Readiness:</strong> Full support for BAA (Business Associate Agreements) and PHI isolation.</li>
              <li><strong>SOC 2 Type II:</strong> Our server environments are certified to meet rigorous security and privacy criteria.</li>
              <li><strong>General Data Protection:</strong> We adhere to GDPR principles for data minimization and user rights across all regions.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. Data Security & Encryption</h2>
            <p>As per our <a href="/security" className="text-[var(--primary)] hover:underline">Security Framework</a>, we employ:</p>
            <ul>
              <li><strong>Military-Grade Encryption:</strong> AES-256 encryption for data at rest and TLS 1.3 for data in transit.</li>
              <li><strong>Zero-Access Protocols:</strong> Zumm employees do not access customer document content unless explicitly authorized for troubleshooting.</li>
              <li><strong>Isolated Environments:</strong> Each Enterprise customer operates within a logically segregated data environment.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Retention and Deletion</h2>
            <p>We retain customer data only as long as necessary to provide our services or as required by law. Enterprise customers may request custom retention policies (e.g., immediate purging after extraction) via their solutions architect.</p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">5. Contact Our Privacy Team</h2>
            <p>For inquiries regarding data protection or DPA requests: </p>
            <div className="flex flex-col gap-1 mt-4">
              <span className="font-bold text-slate-900 dark:text-white">Zumm Inc. Legal Department</span>
              <span className="text-slate-600 dark:text-gray-400">100 Innovation Drive, San Francisco, CA 94105</span>
              <span className="text-[var(--primary)] font-medium">privacy@zumm.ai</span>
            </div>
          </section>
        </motion.div>
      </div>
    </div>
  );
}
